# Generated by Django 4.1.4 on 2022-12-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Contact',
            field=models.IntegerField(),
        ),
    ]
