# Generated by Django 4.1.4 on 2022-12-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_student_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Due',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='Paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='Total',
            field=models.IntegerField(default=0),
        ),
    ]
