# Generated by Django 4.1.4 on 2022-12-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_student_due_student_paid_student_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=20)),
                ('Contact', models.IntegerField()),
                ('Joining_dt', models.DateField()),
                ('Education', models.CharField(max_length=20)),
                ('Employee_id', models.IntegerField()),
                ('Work_exp', models.CharField(max_length=50)),
                ('Package', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
